CREATE DATABASE bd_goodlife;
USE bd_goodlife;

CREATE TABLE tb_medico(
TB_MEDICO_CRM INTEGER NOT NULL PRIMARY KEY,
TB_MEDICO_NOME VARCHAR(140) NOT NULL,
TB_MEDICO_ESPECIALIZACAO VARCHAR(50) NOT NULL
);

CREATE TABLE tb_cliente(
TB_CLIENTE_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
TB_CLIENTE_LOGIN VARCHAR(200) NOT NULL,
TB_CLIENTE_SENHA INTEGER NOT NULL,
TB_CLIENTE_DT_NASC DATE NOT NULL,
TB_CLIENTE_EMAIL VARCHAR(130) NULL,
TB_CLIENTE_TIPO_SANGUINEO VARCHAR(8) NOT NULL,
TB_CLIENTE_TELEFONE VARCHAR(14) NOT NULL
);

CREATE TABLE tb_funcionario(
TB_FUNCIONARIO_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
TB_FUNCIONARIO_EMAIL Varchar(150) not null,
TB_FUNCIONARIO_NOME varchar(100) not null,
TB_FUNCIONARIO_SENHA INTEGER NOT NULL
);

CREATE TABLE tb_agendamento (
TB_AGENDAMENTO_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
TB_AGENDAMENTO_DT_CONSULTA DATE NOT NULL,
TB_AGENDAMENTO_HORARIO TIME NOT NULL,
TB_AGENDAMENTO_PRECO DECIMAL(10,2) NOT NULL,
TB_AGENDAMENTO_RETORNO BOOL NOT NULL,
TB_AGENDAMENTO_ESP VARCHAR(30) NOT NULL,
TB_FUNCIONARIO_ID INTEGER NOT NULL,
CONSTRAINT fk_tb_agendamento_pk_tb_funcionario FOREIGN KEY (TB_FUNCIONARIO_ID) REFERENCES tb_funcionario(TB_FUNCIONARIO_ID),
TB_CLIENTE_ID INTEGER NOT NULL,
CONSTRAINT fk_tb_agendamento_pk_tb_cliente FOREIGN KEY (TB_CLIENTE_ID) REFERENCES tb_cliente(TB_CLIENTE_ID),
TB_MEDICO_CRM INTEGER NOT NULL,
CONSTRAINT fk_tb_agendamento_pk_tb_medico FOREIGN KEY (TB_MEDICO_CRM) REFERENCES tb_medico(TB_MEDICO_CRM)
);

CREATE TABLE TB_SENHA(
TB_SENHA_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
TB_SENHA_DESCRICAO INTEGER NOT NULL,
TB_SENHA_TIPO VARCHAR(30) NOT NULL
);


INSERT INTO TB_SENHA(
TB_SENHA_DESCRICAO,
TB_SENHA_TIPO
) VALUES (
1897,
"Funcionário"
);

select TB_SENHA_DESCRICAO from TB_SENHA where TB_SENHA_ID = 1;
select * from tb_funcionario;
/*INSERT INTO TB_FUNCIONÁRIO*/
INSERT INTO TB_FUNCIONARIO(
TB_FUNCIONARIO_EMAIL,
TB_FUNCIONARIO_NOME,
TB_FUNCIONARIO_SENHA
) VALUES(
"rgbatista0@gmail.com",
"Raphael",
1234
),
(
"gabriel@yahoo.com",
"Gabriel",
4321
), (
"carlo@hotmail.com",
"Carlinhos",
4311
);

/*INSERT INTO TB_MÉDICO*/
INSERT INTO TB_MEDICO(
TB_MEDICO_CRM,
TB_MEDICO_NOME,
TB_MEDICO_ESPECIALIZACAO
) VALUES
(
1234,
"Cleber",
"Gastroenterologista"
),(
4321,
"Osvaldo",
"Cardiologista"
),(
3214,
"Fernando",
"Herbiatra"
);

/*INSERT INTO TB_CLIENTE*/
INSERT INTO TB_CLIENTE(
TB_CLIENTE_LOGIN,
TB_CLIENTE_SENHA,
TB_CLIENTE_DT_NASC,
TB_CLIENTE_EMAIL,
TB_CLIENTE_TIPO_SANGUINEO,
TB_CLIENTE_TELEFONE
) VALUES(
'Claudio',
12345,
'2000-11-11',
"Claudio@yahoo.com",
"O-",
"11987654321"
), (
'Rogério',
43215,
'1980-09-02',
"Roger@gmail.com",
"O+",
"1154383-9423"
), (
'Pedro',
98423,
'1970-01-25',
"Pedro@hotmail.com",
"AB+",
"11987654321"
);

SELECT * FROM tb_medico;
INSERT INTO tb_agendamento(
TB_AGENDAMENTO_DT_CONSULTA,
TB_AGENDAMENTO_HORARIO,
TB_AGENDAMENTO_PRECO,
TB_AGENDAMENTO_RETORNO,
TB_AGENDAMENTO_ESP,
TB_FUNCIONARIO_ID,
TB_CLIENTE_ID,
TB_MEDICO_CRM
) VALUES(
"2023-10-10",
"14:00",
150.00,
"true",
"Gastroenterologista",
1,
1,
1234
),(
"2023-11-09",
"15:00",
75.00,
"false",
"herbiatra",
1,
3,
3214
),(
"2023-11-08",
"15:30",
75.00,
"true",
"Herbiatra",
1,
2,
3214
);

SELECT a.TB_AGENDAMENTO_ID,
a.TB_AGENDAMENTO_DT_CONSULTA,
a.TB_AGENDAMENTO_HORARIO,
a.TB_AGENDAMENTO_PRECO,
a.TB_AGENDAMENTO_RETORNO,
a.TB_AGENDAMENTO_ESP,
a.TB_FUNCIONARIO_ID,
c.TB_CLIENTE_LOGIN,
a.TB_MEDICO_CRM
FROM tb_agendamento AS a
INNER JOIN TB_CLIENTE AS c
on c.TB_CLIENTE_ID = a.TB_CLIENTE_ID
where c.TB_CLIENTE_LOGIN = "Claudio" AND a.TB_AGENDAMENTO_ESP = "Gastroenterologista"; 


select * from tb_agendamento;

SELECT
A.TB_AGENDAMENTO_ID AS ID,
A.TB_AGENDAMENTO_DT_CONSULTA AS DT_CONSULTA,
A.TB_AGENDAMENTO_HORARIO AS HORARIO,
A.TB_AGENDAMENTO_PRECO AS PRECO,
A.TB_AGENDAMENTO_RETORNO AS RETORNO,
A.TB_AGENDAMENTO_ESP AS ESPECIALIZACAO,
F.TB_FUNCIONARIO_NOME AS NOME_FUNCIONARIO,
C.TB_CLIENTE_LOGIN AS NOME_CLIENTE,
M.TB_MEDICO_NOME AS NOME_MEDICO,
M.TB_MEDICO_ESPECIALIZACAO AS ESPECIALIZACAO
FROM TB_AGENDAMENTO AS A
INNER JOIN TB_MEDICO AS M ON A.TB_MEDICO_CRM = M.TB_MEDICO_CRM
INNER JOIN TB_FUNCIONARIO AS F ON A.TB_FUNCIONARIO_ID = F.TB_FUNCIONARIO_ID
INNER JOIN TB_CLIENTE AS C ON A.TB_CLIENTE_ID = C.TB_CLIENTE_ID;


